#!/bin/bash

echo "Set $1 sample directory"
case "$(uname -s)" in
    Linux*)
        echo "Linux OS detected"
        LD_PRELOAD="/usr/local/lib/fakenect/libfakenect.so" \
        ${@:1}
    ;;
    Darwin*)
        echo "Mac OS detected"
        DYLD_INSERT_LIBRARIES="/Users/kosta/src/OpenISS/libfreenect/build/lib/libfreenect.dylib" \
        ${@:1}
    ;;
    *)
        echo "Incompatible OS"
esac
